# Execute following commands before using the newly created ubuntu user
#ssh-keyscan 192.168.10.10 >> ~/.ssh/known_hosts
#ssh-keyscan 192.168.10.11 >> ~/.ssh/known_hosts
#ssh-keyscan 192.168.10.12 >> ~/.ssh/known_hosts
#ssh-keyscan 192.168.10.13 >> ~/.ssh/known_hosts

- hosts: all
  become: yes
  tasks:
    - name: creating ubuntu user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: ubuntu for passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
