  - name: Get join command from master
    hosts: masters
    become: yes
    gather_facts: false
    tasks:
      - name: get join command
        shell: kubeadm token create --print-join-command
        register: join_command_raw
      - debug:
          var: join_command_raw
      - name: set join command
        set_fact:
          join_command: "{{ join_command_raw.stdout_lines[0] }}"

  #kubeadm join 10.0.2.15:6443 --token bkqxws.3mqj195y0g9job93  --discovery-token-ca-cert-hash sha256:fe97789fb2cc9feda1aa206b333383bff95e109b06521e7e6fcb0bef33f5493a

  - name: Run join command from worker
    hosts: workers
    become: yes
    tasks:
      - name: join cluster
        shell: "{{ hostvars['masters']['join_command'] }} >> node_joined.txt"
        args:
          chdir: $HOME
          creates: node_joined.txt