IMAGE_NAME = "bento/ubuntu-18.04"
NODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.10.10"
        master.vm.hostname = "k8s-master"
    end

    (1..NODES).each do |i|
        config.vm.define "k8s-worker#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.10.#{i + 10}"
            node.vm.hostname = "k8s-worker#{i}"
        end
    end
end
