apiVersion: extensions/v1beta1
kind: Deployment                                
metadata:
  name: user-management
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: devops-user-api
    spec:
      containers:
        - image: kannanc70/devops-python
          imagePullPolicy: Always
          name: devops-python
          ports:
            - containerPort: 5000
          env:
            - name: db_name
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_name
            - name: db_username
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_username
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: db_host
              value: devops-mysql
            - name: FLASK_DEBUG
              value: '1'