apiVersion: v1
kind: Pod
metadata:
  name: devops-mysql
  labels:
    app: devops-db
spec: 
  containers:
    - image: kannanc70/devops-mysql 
      name: devops-mysql
      ports:
        - containerPort: 80
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: db_password